### ISSUE TITLE
Could we have a java7 compatible release?

### ISSUE THREAD

**Issue by insano10** [LMAX-Exchange/elementspec#1]
For those of us that aren't as bleeding edge could you please create a release compiled for java 7 as I'm not in a place to upgrade java just yet but still want to use elementspec.

Cheers!

**Comment by ajsutton** [comment]
Unfortunately the code uses quite a few Java 8 features so can't just be recompiled.  I think the code could be converted to Java 7 compatibility without losing too much readability so if you or someone else really wanted this I'd be happy to accept a pull request but I suspect the effort is probably better spent upgrading to Java 8. :)
